### ISSUE TITLE
Miui Camera Unsupported? 

### ISSUE THREAD

**Issue by rad1914** [diamachi/munch_releases#1]
Hello,

I recently installed Awaken3.5-Build1 and overall the build is stable and lightweight. However, I have encountered an issue with the Miui cam module, which can be found at this link: (https://drive.google.com/file/d/1FhDS9ns0ruQjBXrdEKo1z-ajd9vHReCc/view). The app doesn't work, always is stopping. I have tried erasing data and granting all required permissions, but i couldn't fix it . I have also tried using the same module in other Vanilla AOSP ROMs, and it worked perfectly.

I really like this ROM, this issue is the only problem I have encountered and I hope it can be fixed soon..

Thank you.

**Comment by diamachi** [comment]
Glad you liked the rom, I originally had added MiCam to the rom but it had many issues so dropped it. I guess commits to support that module aren't in my trees. Is there a github or gitlab of the module where I can check it?

Awaken is not releasing March update afaik. So you might have to wait for april update, as I am already planning on adding MiCam.

If you really need MiCam, you can join the PocoF4 group on telegram, many users are using different modules. You can check whichever works.

**Comment by rad1914** [comment]
Well, I don't actually have the repository where the module I sent was developed, just the Google Drive link I've sent. And I haven't tried installing any other modules, just the one I mentioned.

Anyway, I wanted to open the issue to also check that this ROM is still being maintained, and I was glad to know that it hasn't been discontinued :) 
I guess I'll wait for the April update to see if in that build miui cam is supported again.. Also I'll join to your Poco F4 support project group of telegram to stay up to date with the news. 

Thx again.

**Comment by diamachi** [comment]
That's fine.
I am a little busy with my uni so haven't updated the trees as well so it would seem like the dev is dead. But I have the device so I will keep updating it till I have it. :))

I will be closing the issue if you don't have any questions. You can ping me on the group as well if you want.

Thanks!
